title: RLT Buyer Guides
description: Structured red light therapy comparisons.
url: ""
baseurl: ""

permalink: pretty

# Asset optimization
sass:
  style: compressed

# Exclude unnecessary files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - README.md
  - Git-2.53.0-64-bit.exe
  - nvm
  - scripts

collections:
  money:
    output: true
    permalink: /money/:name/
  guides:
    output: true
    permalink: /guides/:name/
